zarperspectiva/authapp/urls.py
from django.urls import path

from authapp.views import (
    SiteUserLoginView,
    SiteUserLogoutView,
    SiteUserRegisterView,
    SiteUserUpdateView,
    SiteUserPasswordResetView,
    send_verify_mail_again,
    ProfileView,
    StudentCreateView,
    StudentEditView,
    StudentDeleteView,
    TermsConditionsView,
)

urlpatterns = [
    path("login/", SiteUserLoginView.as_view(), name="login"),
    path("logout/", SiteUserLogoutView.as_view(), name="logout"),
    path("register/", SiteUserRegisterView.as_view(), name="register"),

    path(
        "verify/<str:email>/<str:activation_key>/",
        SiteUserRegisterView.verify,
        name="verify",
    ),
    path("send-verify/<str:email>", send_verify_mail_again, name="send-verify"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("update-profile/", SiteUserUpdateView.as_view(), name="update-profile"),

    path("create-student/", StudentCreateView.as_view(), name="create-student"),
    path("update-student/<int:pk>/", StudentEditView.as_view(), name="update-student"),
    path("delete-student/<int:pk>/", StudentDeleteView.as_view(), name="delete-student"),

    path("terms-conditions/", TermsConditionsView.as_view(), name="terms-conditions"),
]

zarperspectiva/mainapp/models.py
import datetime

from django.conf import settings
from django.db import models
from tinymce.models import HTMLField

from authapp.models import Student


class SiteSettings(models.Model):
    site_info = HTMLField(
        verbose_name='информация о сайте',
        default='Информация',
    )
    admin_letter_template = HTMLField(
        verbose_name='шаблон письма администратору',
        default='Поступила новая заявка',
    )
    client_letter_template = HTMLField(
        verbose_name='шаблон письма клиенту',
        default='Спасибо за заявку',
    )
    schedule_url = models.CharField(
        verbose_name='ссылка на расписание',
        default='',
        max_length=150,
    )
    calendar_url = models.CharField(
        verbose_name='ссылка на календарь',
        default='',
        max_length=150,
    )
    price_url = models.CharField(
        verbose_name='ссылка на прайс',
        default='',
        max_length=150,
    )
    admin_photo = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        verbose_name='фото администратора',
    )
    admin_email = models.EmailField(
        verbose_name='email администратора',
        null=False,
        default='zarperspectiva@gmail.com'
    )
    admin_phone = models.CharField(
        verbose_name='телефон администратора',
        default='+7-919-367-2831',
        max_length=50,
    )
    address = models.CharField(
        verbose_name='адрес центра',
        default='г. Заречный, ул. Ленинградская, 29А',
        max_length=150,
    )
    vk_link = models.CharField(
        verbose_name='ссылка на ВК',
        default='https://vk.com/public.cpperspektiva',
        max_length=150,
    )
    contacts_info = HTMLField(
        verbose_name='информация о контактах',
        default='На ваши вопросы всегда ответит администратор центра Ольга Валерьевна. Тел. +7-919-367-2831 (с 18 августа по 26 мая по будням с 15.00 до 20.00)',
    )
    center_info = HTMLField(
        verbose_name='информация о центре',
        default='',
    )
    terms_conditions = models.TextField(
        verbose_name='Политика конфиденциальности и обработки персональных данных',
        default=''
    )

    class Meta:
        verbose_name = 'Настройки сайта'


class Subject(models.Model):
    title = models.CharField(
        verbose_name='название',
        null=False,
        max_length=40,
    )
    pic = models.ImageField(
        upload_to='subjects/',
        null=True,
        blank=True,
        verbose_name='фон предмета',
    )
    slug = models.SlugField(
        max_length=255, unique=True, db_index=True, verbose_name="URL",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'


class Teacher(models.Model):
    first_name = models.CharField(
        verbose_name='имя',
        max_length=30,
        null=False,
    )
    second_name = models.CharField(
        verbose_name='отчество',
        max_length=30,
        null=False,
    )
    last_name = models.CharField(
        verbose_name='фамилия',
        max_length=40,
        null=False,
    )
    pic = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        verbose_name='фото',
    )

    info = HTMLField(
        verbose_name='информация',
        null=True,
        default='',
    )

    subjects = models.ManyToManyField(Subject)

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.second_name}'

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'


class Age(models.Model):
    age = models.CharField(
        verbose_name='возраст',
        null=False,
        max_length=30,
    )

    def __str__(self):
        return self.age

    class Meta:
        verbose_name = 'Возрастная категория'
        verbose_name_plural = 'Возрастные категории'


class AcademicHour(models.Model):
    duration = models.IntegerField(
        verbose_name='длительность урока',
        null=False,
        default=45,
    )
    price_once = models.CharField(
        verbose_name='разовая оплата (групп)',
        null=False,
        max_length=32,
    )
    price_month = models.CharField(
        verbose_name='абонемент 4 занятия (групп)',
        null=False,
        max_length=32,
    )
    price_once_ind = models.CharField(
        verbose_name='разовая оплата (индивидуально)',
        null=False,
        max_length=32,
        default=750,
    )
    price_month_ind = models.CharField(
        verbose_name='абонемент 4 занятия (индивидуально)',
        null=False,
        max_length=32,
        default=2550,
    )

    def __str__(self):
        return f'{self.duration} минут'

    class Meta:
        verbose_name = 'академический час'
        verbose_name_plural = 'академические часы'
        ordering = ['duration']


class Course(models.Model):
    title = models.CharField(
        verbose_name='название курса',
        max_length=100,
        null=False,
    )
    info = HTMLField(
        verbose_name='информация о курсе',
        blank=True,
        default='',
    )
    subject = models.ManyToManyField(
        Subject,
        verbose_name='предмет',
        related_name='subject',
    )
    age = models.ManyToManyField(
        Age,
        verbose_name='возраст',
        related_name='ages',
    )
    teacher = models.ForeignKey(
        Teacher,
        verbose_name='преподаватель',
        null=True,
        on_delete=models.SET_NULL,
    )
    # price_once_alone = models.IntegerField(
    #     verbose_name='Разовая оплата за занятие (уст.)',
    #     default=600,
    # )
    # price_pass_group = models.IntegerField(
    #     verbose_name='Цена за месяц по абонементу (уст.)',
    #     default=1400,
    # )
    # duration = models.IntegerField(
    #     verbose_name='длительность занятия (уст.)',
    #     default=60,
    # )
    academic_hour = models.ForeignKey(
        AcademicHour,
        verbose_name='длительность занятия',
        related_name='academic_hour',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    count_a_week = models.IntegerField(
        verbose_name='занятий в неделю',
        default=1,
    )
    count_overall = models.IntegerField(
        verbose_name='занятий всего',
        default=10,
    )
    group_size = models.CharField(
        verbose_name='размер группы',
        blank=True,
        max_length=30,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['title']


class Pupil(models.Model):
    parent_surname = models.CharField(
        verbose_name='Фамилия заказчика',
        max_length=50,
        null=False,
        blank=False,
    )

    parent_name = models.CharField(
        verbose_name='Имя заказчика',
        max_length=50,
        null=False,
        blank=False,
    )

    parent_second_name = models.CharField(
        verbose_name='Отчество заказчика',
        max_length=50,
        null=False,
        blank=False,
    )

    phone_parent = models.CharField(
        verbose_name='Телефон заказчика',
        max_length=12,
        null=False,
        blank=False,
    )

    address_parent = models.CharField(
        verbose_name='адрес',
        max_length=256,
        null=False,
        blank=False,
        default='не указан',
    )

    e_mail_parent = models.EmailField(
        verbose_name='Электронная почта заказчика',
        null=False,
        blank=False,
    )

    surname_pupil = models.CharField(
        verbose_name='Фамилия ученика',
        max_length=50,
        null=False,
        blank=False,
    )

    name_pupil = models.CharField(
        verbose_name='Имя ученика',
        max_length=50,
        null=False,
        blank=False,
    )

    second_name_pupil = models.CharField(
        verbose_name='Отчество ученика',
        max_length=50,
    )

    birthday_pupil = models.DateField(
        verbose_name='дата рождения ученика',
        null=False,
    )

    school_pupil = models.CharField(
        verbose_name='Место учебы',
        max_length=100,
    )

    phone_pupil = models.CharField(
        verbose_name='Телефон ученика',
        max_length=12,
        null=True,
        blank=True,
    )

    e_mail_pupil = models.EmailField(
        verbose_name='Электронная почта ученика',
        null=True,
        blank=True,
    )

    courses = models.ManyToManyField(Course)

    sign_up_date = models.DateField(
        verbose_name='дата записи',
        auto_now_add=True,
    )

    student = models.ForeignKey(
        Student,
        verbose_name='ученик',
        related_name='records',
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True,
    )

    comment = models.TextField(
        verbose_name='комментарий',
        max_length=256,
        null=True,
        blank=True,
        default='',
    )

    def __str__(self):
        return f'{self.surname_pupil} {self.name_pupil} {self.second_name_pupil}'

    class Meta:
        verbose_name = 'Запись на курс'
        verbose_name_plural = 'Записи на курсы'


class Review(models.Model):
    ROLES = [
        ('Родитель', 'Родитель'),
        ('Ученик', 'Ученик'),
    ]

    review_text = HTMLField(
        verbose_name='Текст отзыва',
        default='Введите текст отзыва.',
    )
    author = models.CharField(
        verbose_name='Автор отзыва',
        max_length=300,
        default='Аноним'
    )

    role = models.CharField(
        verbose_name='Роль',
        max_length=20,
        choices=ROLES,
        default='Родитель'
    )

    def __str__(self):
        return self.review_text

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

zarperspectiva/mainapp/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django import forms

from mainapp.models import Pupil, Subject


class DateInput(forms.DateInput):
    input_type = 'date'


class CreateRecordForm(forms.ModelForm):
    """
    Форма создания записи на курс
    """
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox, label="Подтвердите что вы не робот!"
    )

    class Meta:
        model = Pupil
        fields = "__all__"
        widgets = {
            'birthday_pupil': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(CreateRecordForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'subjects':
                field.widget.attrs["class"] = ""
            else:
                field.widget.attrs["class"] = "form-control"
            field.help_text = ""

zarperspectiva/mainapp/templates/mainapp/anonymous_record.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-1 mt-2">
  <h2 class="text-center">Запись на курсы</h2>
  <div class="container col-12 col-md-5 col-lg-4 mt-4 mb-4">
    <form method="post">
      {% csrf_token %}
      <hr>
      <h4>Информация о Заказчике:</h4>
        {% for field in form %}
        {% if 'parent' in field.name %}
        {{ field.errors }}
        {{ field.label }}
        {{ field }}
        {% endif %}
        {% endfor %}

      <br>
       <hr>
      <div>
        <h4>Информация об Ученике:</h4>
        {% for field in form %}
        {% if 'pupil' in field.name %}
        {{ field.errors }}
        {{ field.label }}
        {{ field }}
        {% endif %}
        {% endfor %}
        Комментарий
        <textarea name="comment" maxlength="254" class="form-control" id="id_comment"></textarea>
      </div>
      {{ form.courses.errors }}
      {% verbatim %}
      <div id="vue">
        <div class="mt-2 mb-2 py-2">
          <div class="mb-3">
            <label for="selectAge" class="fw-bold me-2">ВОЗРАСТ</label>
            <select v-model="selectedAge" id="selectAge" @change="getAvailableSubjects" required>
              <option value="">Все</option>
              <option v-for="age in ages" :value="age.id">{{ age.age }}</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="selectSubject" class="fw-bold me-1">ПРЕДМЕТ</label>
            <select v-model="selectedSubject" id="selectSubject" class="me-3" @change="getCourses"
              :disabled="subjectsDisabled">
              <option value="">Все</option>
              <option v-for="subject in subjects" :value="subject.id" class="text-capitalize">
                {{ subject.title }}
              </option>
            </select>
          </div>
        </div>
        <p v-if="showWarning">Для отображения курсов выберите возраст и предмет</p>
        <div v-for="course in courses">
          <div>
            <input type="checkbox" :id="course.id" :value="course.id" name="courses" v-model="course.checked">
            <label :for="course.id">{{ course.title }} (<span v-for="subj in course.subject">{{ subj.title }}</span>)</label>
          </div>
        </div>
      </div>
      {% endverbatim %}
      <div class="mt-2 mb-3">
      <a href="{% url 'auth:terms-conditions' %}">Нажимая кнопку "Записаться", я подтверждаю согласие с <span style="color:blue">
        политикой конфиденциальности и обработки персональных данных</span></a>
      </div>
      {{ form.captcha.errors }}
      {{ form.captcha.label }}
      {{ form.captcha }}
      <br>
      <input type="submit" value="Записаться" class="col-12 btn btn-primary">
    </form>
    <script type="text/javascript">
      new Vue({
        el: '#vue',
        data: {
          showWarning: true,
          subjectsDisabled: true,
          courses: [],
          subjects: [],
          ages: [],
          selectedSubject: '',
          selectedAge: '',
        },
        methods: {
          getCourses() {
            let subjParam = '';
            if (this.selectedAge != '') {
              if (this.selectedSubject != '') {
                subjParam = '&subjId=' + this.selectedSubject
              };
              axios
                .get('/api/courses?ageId=' + this.selectedAge + subjParam)
                .then(response => {
                  this.courses = response.data;
                  if (this.courses.length > 0) { this.showWarning = false }
                  else { this.showWarning = true };
                });
            }
          },
          getAvailableSubjects() {
            this.subjectsDisabled = false;
            this.selectedSubject = '';
            this.courses = [];
            axios
              .get('/api/subjects?ageId=' + this.selectedAge)
              .then(response => {
                this.subjects = response.data;
                this.getCourses()
                if (this.courses.length > 0) { this.showWarning = false }
                else { this.showWarning = true };
              });
          },
        },
        created() {
          axios
            .get('/api/ages/')
            .then(response => {
              this.ages = response.data;
            });
          this.getUser();
        }
      }
    )
    </script>
  </div>
</section>
{% endblock %}

zarperspectiva/mainapp/templates/mainapp/contacts.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
    <div class="container col-lg-10">
      <div class="row">
          <h3>Контакты</h3>
          <p>{{ address }}<br>
          {{ admin_phone }}</p>
          <hr>
          <div class="d-flex row">
              <div class="ms-2 me-3 mb-3 col-sm-12 col-lg-3 text-center">
                <img src="/media/{{ admin_photo }}" class="rounded-circle w-100" style="max-width:200px;">
              </div>
              <div class="d-flex flex-column justify-content-end col-sm-12 col-lg-8">
                  {{ contacts_info | safe }}
              </div>
          </div>
      </div>
      <hr>
      <p><i class="fab fa-vk"></i> <a href="{{ vk_link }}">Мы ВКонтакте</a></p>
      <p><i class="fa fa-envelope"></i> <a href="mailto:{{ admin_email }}">{{ admin_email }}</a></p>
    </div>
</section>

{% endblock %}

zarperspectiva/mainapp/templates/mainapp/export.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-3">
    <div class="container col-lg-8">
        <p><a href="{% url 'staff:index' %}">К панели администратора</a></p>
      <div class="row">
          <h3>Экспорт данных</h3>
          <div><a href="{% url 'export-records' %}">Экспортировать список записей</a></div>
      </div>
    </div>
</section>

{% endblock %}

zarperspectiva/mainapp/templates/mainapp/record_complete.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
    <div class="container col-12 col-md-5 col-lg-4 mt-4 mb-4">
      <div class="row text-center">
            <h3>Благодарим за запись!</h3>
            <p>В ближайшее время с Вами свяжется администратор для уточнения информации.</p>
            <a href="{% url 'index' %}" class="">на главную</a>
            </div>
        </div>
</section>
{% endblock %}

zarperspectiva/mainapp/templates/mainapp/record_for_course.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-1 mt-2">
  <h2 class="text-center">Запись на курсы</h2>
  <div class="container col-12 col-md-5 col-lg-4 mt-4 mb-4">
    {% if not user.is_authenticated %}
    <div class="mb-3 text-center">
      <a href="{% url 'auth:login' %}"><u>Войдите</u></a> или <a href="{% url 'auth:register' %}"><u>зарегистрируйтесь</u></a>, чтобы сохранить данные о записи
      <br>
      <div class="mt-2"><a href="{% url 'anonymous-record' %}"><button class="btn btn-primary">Продолжить без регистрации</button></a></div>
    </div>
    {% else %}
    <form method="post">
      {% csrf_token %}
      {% if not user.students.all %}
        <div class="text-danger"><a class="text-danger" href="{% url 'auth:create-student' %}?next=/record-for-courses/"><u>Добавьте</u></a> данные об учениках, чтобы записаться!</div>
      {% endif %}
      <h4>Информация о Заказчике:</h4>
      <a href="{% url 'auth:update-profile' %}" class="me-2"><u>Изменить</u></a>
      <hr>
      <div id="user-vue">
      {% verbatim %}
        Фамилия заказчика
        <input type="text" name="parent_surname" maxlength="50" class="form-control" :value="user.last_name" required="" id="id_parent_surname" readonly>
        Имя заказчика
        <input type="text" name="parent_name" maxlength="50" class="form-control" :value="user.first_name" required="" id="id_parent_name" readonly>
        Отчество заказчика
        <input type="text" name="parent_second_name" maxlength="50" class="form-control" :value="user.second_name" required="" id="id_parent_second_name" readonly>
        Телефон заказчика
        <input type="text" name="phone_parent" maxlength="12" class="form-control" :value="user.phone" required="" id="id_phone_parent" readonly>
        Электронная почта заказчика
        <input type="email" name="e_mail_parent" maxlength="254" class="form-control" :value="user.email" required="" id="id_e_mail_parent" readonly>
        Адрес заказчика
        <input type="text" name="address_parent" value="не указан" maxlength="256" class="form-control" :value="user.address" required="" id="id_address_parent" readonly>
      </div>
      <br>
       <hr>
      <div id="students-vue">
        <h4>Информация об Ученике:</h4>
        <select v-if="students.length" v-model="studentId" id="selectStudent"  @change="chooseStudents">
          <option  v-for="(student, index) in students" :value="index">{{ student.last_name }} {{ student.first_name }}</option>
        </select>

        <a :href="'/auth/create-student/?next=/record-for-courses/'" class="me-2"><u>Добавить ученика</u></a>

        <a v-if="student.id" :href="'/auth/update-student/'+ student.id + '?next=/record-for-courses/'" class="me-2"><u>Изменить</u></a>
        <br>
        <div v-if="students.length">
          <input type="hidden" name="student" :value="student.id">
          Фамилия ученика
          <input type="text" name="surname_pupil" maxlength="50" class="form-control" :value="student.last_name" required="" id="id_surname_pupil" readonly>
          Имя ученика
          <input type="text" name="name_pupil" maxlength="50" class="form-control" :value="student.first_name" required="" id="id_name_pupil" readonly>
          Отчество ученика
          <input type="text" name="second_name_pupil" maxlength="50" class="form-control" :value="student.second_name" required="" id="id_second_name_pupil" readonly>
          Дата рождения ученика
          <input type="date" name="birthday_pupil" class="form-control" required="" :value="student.birthday" id="id_birthday_pupil" readonly>
          Место учебы
          <input type="text" name="school_pupil" maxlength="100" class="form-control" :value="student.school" required="" id="id_school_pupil" readonly>
          Телефон ученика
          <input type="text" name="phone_pupil" maxlength="12" class="form-control" :value="student.phone" id="id_phone_pupil" readonly>
          Электронная почта ученика
          <input type="email" name="e_mail_pupil" maxlength="254" class="form-control" :value="student.email" id="id_e_mail_pupil" readonly>
          Комментарий
          <textarea name="comment" maxlength="254" class="form-control" id="id_comment"></textarea>
        </div>
      </div>
      {% endverbatim %}
      {{ form.courses.errors }}
      {% verbatim %}
      <div id="vue">
        <div class="mt-2 mb-2 py-2">
          <div class="mb-3">
            <label for="selectAge" class="fw-bold me-2">ВОЗРАСТ</label>
            <select v-model="selectedAge" id="selectAge" @change="getAvailableSubjects" required>
              <option value="">Все</option>
              <option v-for="age in ages" :value="age.id">{{ age.age }}</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="selectSubject" class="fw-bold me-1">ПРЕДМЕТ</label>
            <select v-model="selectedSubject" id="selectSubject" class="me-3" @change="getCourses"
              :disabled="subjectsDisabled">
              <option value="">Все</option>
              <option v-for="subject in subjects" :value="subject.id" class="text-capitalize">
                {{ subject.title }}
              </option>
            </select>
          </div>
        </div>
        <p v-if="showWarning">Для отображения курсов выберите возраст и предмет</p>
        <div v-for="course in courses">
          <div>
            <input type="checkbox" :id="course.id" :value="course.id" name="courses" v-model="course.checked">
            <label :for="course.id">{{ course.title }} (<span v-for="subj in course.subject">{{ subj.title }}</span>)</label>
          </div>
        </div>
      </div>
      {% endverbatim %}
      <div class="mt-2 mb-3">
      <a href="{% url 'auth:terms-conditions' %}">Нажимая кнопку "Записаться", я подтверждаю согласие с <span style="color:blue">
        политикой конфиденциальности и обработки персональных данных</span></a>
      </div>
      {{ form.captcha.errors }}
      {{ form.captcha.label }}
      {{ form.captcha }}
      <br>
      <input type="submit" value="Записаться" class="col-12 btn btn-primary">
    </form>
    <script type="text/javascript">
      new Vue({
        el: '#vue',
        data: {
          showWarning: true,
          subjectsDisabled: true,
          courses: [],
          subjects: [],
          ages: [],
          selectedSubject: '',
          selectedAge: '',
        },
        methods: {
          getCourses() {
            let subjParam = '';
            if (this.selectedAge != '') {
              if (this.selectedSubject != '') {
                subjParam = '&subjId=' + this.selectedSubject
              };
              axios
                .get('/api/courses?ageId=' + this.selectedAge + subjParam)
                .then(response => {
                  this.courses = response.data;
                  if (this.courses.length > 0) { this.showWarning = false }
                  else { this.showWarning = true };
                });
            }
          },
          getAvailableSubjects() {
            this.subjectsDisabled = false;
            this.selectedSubject = '';
            this.courses = [];
            axios
              .get('/api/subjects?ageId=' + this.selectedAge)
              .then(response => {
                this.subjects = response.data;
                this.getCourses()
                if (this.courses.length > 0) { this.showWarning = false }
                else { this.showWarning = true };
              });
          },
        },
        created() {
          axios
            .get('/api/ages/')
            .then(response => {
              this.ages = response.data;
            });
          this.getUser();
        }
      }
    )

    new Vue(
      {
        el: '#user-vue',
        data: {
          user: {},
        },
        methods: {
          getUser() {
              axios
                .get('/api/user/')
                .then(response => {
                  this.user = response.data[0];
                });
          },
        },
        created() {
          console.log('===========================');
          this.getUser();
        }
      }
    )

    new Vue(
      {
        el: '#students-vue',
        data: {
          students: [],
          student: {},
          studentId: null,
        },
        methods: {
          getStudents() {
              axios
                .get('/api/students/')
                .then(response => {
                  this.students = response.data;
                });
          },
        },
        created() {
          this.getStudents();
        },
        computed: {
          chooseStudents() {
            console.log(this.studentId);
            if (this.studentId != null) {
              this.student = this.students[this.studentId]
            }
            ;
            console.log(this.student);
          }
        }
      })
    </script>
  </div>
  {% endif %}
</section>
{% endblock %}

zarperspectiva/mainapp/templates/mainapp/schedule.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
    <div class="container col-lg-10">
      <div class="row">
          <h3>Полезная информация</h3>
          <div><a href="{{ content.schedule_url }}"><u>Расписание занятий</u></a></div>
          <div><a href="{{ content.calendar_url }}"><u>Календарь занятий</u></a></div>
          <br>
<!--          <div><a href="{% url 'export-courses' %}"><u>Скачать прайс-лист</u></a></div>-->
          <div><a href="{{ content.price_url }}"><u>Скачать прайс-лист</u></a></div>
      </div>
      <div class="row mt-3 col-lg-8">
          <h3>О центре</h3>
          <div class="text-justify">{{ content.center_info|safe }}</div>
      </div>
    </div>
</section>

{% endblock %}

zarperspectiva/mainapp/templates/mainapp/teachers.html
{% extends 'zarperspectiva/base.html' %}
{% load static %}

{% block content %}
<section class="mb-4 pt-5">
<div class="container">
    <div class="row">
        <h1 class="mb-5"> НАШИ УЧИТЕЛЯ </h1>
        {% for teacher in teachers %}

              <div class="text-center col-sm-6 col-lg-3 mb-3">
                  <a href="{% url 'teacher' teacher.pk %}">
                      <div><img class="avatar-pic" src="/media/{{ teacher.pic }}" alt="">
                        <h3 class="fw-normal font-base lh-1 text-black mt-3 mb-0"> {{ teacher.last_name }} <br> {{teacher.first_name}} <br> {{teacher.second_name}} </h3>
                        {% for subj in teacher.subjects.all %}
                        <p class="mb-0">{{ subj.title }}</p>
                        {% endfor %}
                      </div>
                  </a>
              </div>

        {% endfor %}
    </div>
</div>
</section>

{% endblock %}